# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
sudo: required
warnings_are_errors: false

addons:
  apt:
    packages:
      - libgit2-dev

r_check_args: '--as-cran'

env:
  - NOT_CRAN=true IS_CHECK=true _R_CHECK_SYSTEM_CLOCK_=false

before_install:
  - sudo apt-get -y install jags
  - sudo apt-get -y install libxml2-dev
addons:
  apt:
    update: true

os:
  - linux

r:
  - oldrel
  - release
  - devel

cran: https://cran.rstudio.com
repos:
  CRAN: https://cran.rstudio.com

r_packages:
  - rjags
  - devtools
  - covr

after_success:
  - Rscript -e 'library(covr); codecov(quiet = FALSE, type = "all")'
