# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
sudo: required
warnings_are_errors: false

r_check_args: '--as-cran'

env:
  - NOT_CRAN=true IS_CHECK=true

before_install:
  - sudo apt-get install jags

os:
  - linux

r:
  - oldrel
  - release
  - devel

cran: http://cran.rstudio.com
repos:
  CRAN: http://cran.rstudio.com

r_packages:
  - rjags
  - devtools
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
