---
title: "What the package can and can't do"
author: "Nicole Erler"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{What the package can and can't do}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Intended functionality:^[<span style = "color:blue">blue</span> indicates possible extensions,
                        <span style = "color:red">red</span> indicates notes and things to check / think about]
## Formula components
### Fixed effects

**linear effects**

* of baseline covariates
* of time-varying covariates
    - no missing values allowed
      <span style = "color:red">(=> should create an error message!)</span>
    - have to be observed together (at the same time points) with the outcome
      <span style = "color:red">(=> check and error message)</span>

    
    
**Interactions**

* 2-way interactions between baseline covariates (may contain missing values)
* 2-way interactions involving time-varying covariates
    - time-varying covariates have to be complete
* <span style = "color:blue"> interactions involving more than 2 variables???
  Only if the syntax can handle it automatically.</span>


**non-linear effects**

* splines (using the `splines` package)
    - only completely observed variables
    - should be possible for baseline, time-varying covariates and the time variable
    - <span style = "color:red"> need to check the functionalities of the
      splines package, if there are other functions than `bs()` and `ns()` that
      should be considered</span>
* `log()`, `sqrt()`, `x^2`, `I()`
    - `log()`, `sqrt()`, `x^2` need to be separately implemented for missing
      values
    - `I()` only for complete variables <span style = "color:red"> are there any
      restrictions for complete variables here?</span>
    - <span style = "color:red"> think about if `x^k` can be implemented more
      general through `pow()` in JAGS</span>
    - when a non-linear function of a variable is used in the main model, the
      same function is used as predictor in the imputation models
    - polynomials of a variable when only some parts of it are in the random effects, 
      e.g. fixed effects: time + time^2, random effects: time
    - <span style = "color:red"> allow for random effects not to be part of the
      fixed effects structure???</span>


**combinations**

* interaction with spline
* interaction with other function


### Random effects
* random intercept and slope
* polynomials of the slope
* other non-linear function of slope
* <span style = "color:blue"> multiple grouping levels??? Would not work at the
  moment because id is expected to have length 1 and the extraction of the id
  variable only finds the last one. </span>
* <span style = "color:blue"> random effects for multiple variables???</span>
* <span style = "color:blue"> missing values in random effects variables???</span>
  variables in the random effects need to be complete at the moment


## Analysis and imputation models
* linear mixed model (outcome only, no imputation of longitudinal variables at this point)
* linear regression (identity link)
* binary regression
    - logit link
    - <span style = "color:blue"> probit link</span>
* multinomial regression
* ordinal (cumulative logistic) regression
* <span style = "color:blue"> poisson regression
    - log link
    - identity link
    - sqrt link
    </span>
* <span style = "color:blue"> Gamma regression
    - log link
    - identity link
    - inverse link
    </span>
* <span style = "color:blue"> Beta regression (for restricted variables?) </span>


## Methods for existing functions
* update (update formula in lme or glm)


## Other
* change imputation methods that are chosen by default
* set reference category for categorical covariates (default is largest category)
* scaling of continuous covariates yes or no (default is yes)
* change order of the imputation models: default is according to proportion of missing values
* JAGS model can be edited
* Option to specify range restrictions for the imputation of continuous variables
* Chose prior values
* chose initial values
* function to generate parameters to follow
* set auxiliary variables
* <span style = "color:red"> Try to automatically remove observations with
missing values in the time variable? </span>
* <span style = "color:blue"> Extend to "BUGS and Stan" </span>


# Implemented and tested

# Notes
* check if it works when there is no data given, but the formula is specified
  using data vectors (e.g. DF$y ~ DF$x | DF$id)
* allow use of data in form of matrix
* check / discuss with DR if the choice of reference also matters for binary variables
