context("help functions prep impmodels")
library("JointAI")

matnames1 <- paste0('x', 1:10)
matnames2 <- c("(Intercept)", paste0('x', 1:10))
matnames3 <- c(paste0('x', 1:4), "(Intercept)", paste0('x', 5:10))

test_that('nbasevars works', {
  expect_equal(get_nbasevars("x3", matnames1, intercept = TRUE), 2)
  expect_equal(get_nbasevars("x3", matnames2, intercept = TRUE), 3)
  expect_equal(get_nbasevars("x3", matnames3, intercept = TRUE), 2)
  expect_equal(get_nbasevars("x8", matnames1, intercept = TRUE), 7)
  expect_equal(get_nbasevars("x8", matnames2, intercept = TRUE), 8)
  expect_equal(get_nbasevars("x8", matnames3, intercept = TRUE), 8)
  expect_equal(get_nbasevars("x81", matnames1, intercept = TRUE), 10)
  expect_equal(get_nbasevars("x81", matnames2, intercept = TRUE), 11)
  expect_equal(get_nbasevars("x81", matnames3, intercept = TRUE), 11)

  expect_equal(get_nbasevars("x3", matnames1, intercept = FALSE), 2)
  expect_equal(get_nbasevars("x3", matnames2, intercept = FALSE), 2)
  expect_equal(get_nbasevars("x3", matnames3, intercept = FALSE), 2)
  expect_equal(get_nbasevars("x8", matnames1, intercept = FALSE), 7)
  expect_equal(get_nbasevars("x8", matnames2, intercept = FALSE), 7)
  expect_equal(get_nbasevars("x8", matnames3, intercept = FALSE), 7)
  expect_equal(get_nbasevars("x81", matnames1, intercept = FALSE), 10)
  expect_equal(get_nbasevars("x81", matnames2, intercept = FALSE), 10)
  expect_equal(get_nbasevars("x81", matnames3, intercept = FALSE), 10)
})

test_that('nlongvars works', {
  expect_equal(get_nlongvars("x3", matnames1, intercept = TRUE), 2)
  expect_equal(get_nlongvars("x3", matnames2, intercept = TRUE), 2)
  expect_equal(get_nlongvars("x3", matnames3, intercept = TRUE), 2)
  expect_equal(get_nlongvars("x8", matnames1, intercept = TRUE), 7)
  expect_equal(get_nlongvars("x8", matnames2, intercept = TRUE), 7)
  expect_equal(get_nlongvars("x8", matnames3, intercept = TRUE), 7)
  expect_equal(get_nlongvars("x81", matnames1, intercept = TRUE), 0)
  expect_equal(get_nlongvars("x81", matnames2, intercept = TRUE), 0)
  expect_equal(get_nlongvars("x81", matnames3, intercept = TRUE), 0)

  expect_equal(get_nlongvars("x3", matnames1, intercept = FALSE), 2)
  expect_equal(get_nlongvars("x3", matnames2, intercept = FALSE), 2)
  expect_equal(get_nlongvars("x3", matnames3, intercept = FALSE), 2)
  expect_equal(get_nlongvars("x8", matnames1, intercept = FALSE), 7)
  expect_equal(get_nlongvars("x8", matnames2, intercept = FALSE), 7)
  expect_equal(get_nlongvars("x8", matnames3, intercept = FALSE), 7)
  expect_equal(get_nlongvars("x81", matnames1, intercept = FALSE), 0)
  expect_equal(get_nlongvars("x81", matnames2, intercept = FALSE), 0)
  expect_equal(get_nlongvars("x81", matnames3, intercept = FALSE), 0)
})


test_that('always intercept if impmeth is not ordinal model', {
  expect_true(intercept_needed('norm', 3, 2))
  expect_true(intercept_needed('norm', 0, 2))
  expect_true(intercept_needed('norm', 0, 0))
  expect_true(intercept_needed('norm', 5, 0))
  expect_true(intercept_needed('lmm', 3, 2))
  expect_true(intercept_needed('lmm', 0, 2))
  expect_true(intercept_needed('lmm', 0, 0))
  expect_true(intercept_needed('lmm', 5, 0))
  expect_true(intercept_needed('lmm', 3, 2))
})

test_that('intercept in ordinal models only when no covariates', {
  expect_true(intercept_needed('cumlogit', 0, 2))
  expect_true(intercept_needed('cumlogit', 0, 0))
  expect_false(intercept_needed('cumlogit', 3, 2))
  expect_false(intercept_needed('cumlogit', 5, 0))
  expect_true(intercept_needed('clmm', 0, 0))
  expect_false(intercept_needed('clmm', 0, 2))
  expect_false(intercept_needed('clmm', 3, 2))
  expect_false(intercept_needed('clmm', 5, 0))
})


test_that('correct columns of Xc are extracted', {
  expect_equal(get_basevar_cols('x3', matnames1, intercept = TRUE), c(1,2))
  expect_equal(get_basevar_cols('x3', matnames1, intercept = FALSE), c(1,2))
  expect_equal(get_basevar_cols('x3', matnames2, intercept = TRUE), c(1,2,3))
  expect_equal(get_basevar_cols('x3', matnames2, intercept = FALSE), c(2,3))
  expect_equal(get_basevar_cols('x3', matnames3, intercept = TRUE), c(1,2))
  expect_equal(get_basevar_cols('x3', matnames3, intercept = FALSE), c(1,2))
  expect_equal(get_basevar_cols('x8', matnames1, intercept = TRUE), 1:7)
  expect_equal(get_basevar_cols('x8', matnames1, intercept = FALSE), 1:7)
  expect_equal(get_basevar_cols('x8', matnames2, intercept = TRUE), 1:8)
  expect_equal(get_basevar_cols('x8', matnames2, intercept = FALSE), 2:8)
  expect_equal(get_basevar_cols('x8', matnames3, intercept = TRUE), 1:8)
  expect_equal(get_basevar_cols('x8', matnames3, intercept = FALSE), c(1:4, 6:8))

  expect_equal(get_basevar_cols('x18', matnames1, intercept = TRUE), 1:10)
  expect_equal(get_basevar_cols('x18', matnames1, intercept = FALSE), 1:10)
  expect_equal(get_basevar_cols('x18', matnames2, intercept = TRUE), 1:11)
  expect_equal(get_basevar_cols('x18', matnames2, intercept = FALSE), 2:11)
  expect_equal(get_basevar_cols('x18', matnames3, intercept = TRUE), 1:11)
  expect_equal(get_basevar_cols('x18', matnames3, intercept = FALSE), c(1:4,6:11))
})
