\name{NEWS}
\title{JointAI News}
\encoding{UTF-8}

\section{Changes in version 0.1.1}{
  \subsection{Bug fixes}{
    \itemize{
      \item removed duplicate plot generated by \code{md_pattern()}
      \item corrected names of imputation methods in help file
      \item fixed bug with scaling when no continuous covariates are in the model
      \item fixed bug in initial value specification for coefficient for auxiliary variables
    }
  }
  \subsection{Small changes}{
    \itemize{
      \item adaptation to new version of \code{md.pattern()} from the mice package
      \item internally change all \code{NaN} to \code{NA}
    }
  }
}
