\name{NEWS}
\title{JointAI News}
\encoding{UTF-8}

\section{Changes in version 0.1.1}{
  \subsection{Bug fixes}{
    \itemize{
      \item removed duplicate plot generated by \code{md_pattern()}
      \item corrected names of imputation methods in help file
      \item fixed bug with scaling when no continuous covariates are in the model or scaling is deselected
      \item fixed bug in initial value specification for coefficient for auxiliary variables
      \item fixed bug in \code{get_MIdat}: imputed values are now filled in in the correct order
      \item variables imputed with \code{lognorm} are now included when extracting an imputed dataset using \code{get_MIdat}
      \item imputed values of transformed variables are now included in imputed datasets created with \code{get_MIdat}
      \item fixed bug that occured when factor labels had non valid names
      \item data matrix is now ordered according to order in user-specified \code{meth} argument
    }
  }
  \subsection{Small changes}{
    \itemize{
      \item adaptation to new version of \code{md.pattern()} from the mice package
      \item internally change all \code{NaN} to \code{NA}
      \item allow for scaling of incomplete covariates with quadratic effects
    }
  }
  \subsection{Extensions}{
    \itemize{
      \item implemented \code{gamma} and \code{beta} imputation methods
    }
  }
}
